/* Proof core. MIT licensed. Pure local data and coaching. No network or runtime dependencies. */
const ProofCore = (() => {
  'use strict';
  const ORDER = Object.freeze(['education', 'experience', 'projects', 'leadership', 'skills', 'extras']);
  const LABELS = Object.freeze({education:'Education', experience:'Experience', projects:'Projects', leadership:'Leadership & Service', skills:'Skills', extras:'Additional Highlights'});
  const SOURCES = Object.freeze({
    course:{label:'Course projects',icon:'book',description:'Research, presentations, campaigns, group projects.',section:'projects',prompt:'Think of a project where your work changed the final result.',role:'Student researcher',org:'Course or project name',action:'Designed a survey to understand student shopping habits',method:'Google Forms and Excel',result:'identified three themes used in the final campaign proposal'},
    work:{label:'Paid work',icon:'briefcase',description:'Part-time jobs, internships, freelance work.',section:'experience',prompt:'What did people trust you to handle, even on a busy day?',role:'Sales associate',org:'Employer or client',action:'Resolved customer order questions during weekend shifts',method:'the store order system',result:'helped customers choose suitable replacements for unavailable items'},
    campus:{label:'Student organizations',icon:'users',description:'Clubs, events, leadership, team responsibilities.',section:'leadership',prompt:'What would have been harder for the group without your contribution?',role:'Events coordinator',org:'Organization name',action:'Coordinated a student organization welcome event',method:'a shared timeline and volunteer assignments',result:'prepared the space and materials before attendees arrived'},
    volunteer:{label:'Volunteering',icon:'heart',description:'Community work, service, causes you care about.',section:'leadership',prompt:'Who benefited from something you organized, explained, or improved?',role:'Volunteer',org:'Organization or community',action:'Organized donated supplies for a community distribution day',method:'an inventory checklist',result:'gave volunteers a clear record of available supplies'},
    personal:{label:'Personal projects',icon:'spark',description:'Side projects, creative work, independent learning.',section:'projects',prompt:'What did you build or figure out without someone assigning it?',role:'Independent project',org:'Project name',action:'Built a personal budget tracker',method:'Excel formulas and pivot tables',result:'created a monthly view of spending by category'},
    community:{label:'Family & community',icon:'home',description:'Real responsibilities beyond a formal job title.',section:'experience',prompt:'Where have you managed schedules, solved problems, or made information clearer?',role:'Operations support',org:'Family business or community role',action:'Maintained a weekly appointment schedule for a family business',method:'a shared calendar and confirmation messages',result:'gave the team one current schedule to work from'}
  });
  const LIMITS = Object.freeze({contact:400, summary:4000, field:4000, text:12000, note:12000, jobDescription:30000, extras:12000, tag:120, tags:40, education:50, experiences:300, contributionsPerExperience:100, contributions:2000, skills:300, variants:40, requirements:100, backupBytes:20000000});
  const STATUSES = Object.freeze(['coursework','proposal','simulation','prototype','tested','live','ongoing','completed']);
  const PRACTICE = Object.freeze(['','guided','independent','repeated','taught']);
  const ATTRIBUTION = Object.freeze(['personal','team','support']);
  const CATEGORIES = Object.freeze(['tools','methods','languages']);
  const CONTACT_KEYS = ['name','email','phone','location','linkedin','portfolio'];
  const INTERVIEW_KEYS = ['situation','task','action','result','lesson'];
  const trim = value => String(value ?? '').trim();
  const own = (object,key) => Object.prototype.hasOwnProperty.call(object,key);
  const esc = value => String(value ?? '').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  function id() { return 'p' + (typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2,12)); }
  function variantFactory(name='General resume') { return {id:id(),name,headline:'',summary:'',order:[...ORDER],style:'modern',density:'comfortable',paperSize:'letter',contributionIds:[],skillIds:[],overrides:{},reviewedOverrides:[],requirements:[],jobDescription:''}; }
  function blank() { const v=variantFactory(); return {app:'proof-resume',version:2,id:id(),revision:0,updatedAt:'',remember:true,contact:Object.fromEntries(CONTACT_KEYS.map(key=>[key,''])),education:[],experiences:[],skills:[],extras:'',variants:[v],selectedVariantId:v.id}; }
  function education() { return {id:id(),school:'',degree:'',dates:'',location:'',gpa:'',courses:'',honors:''}; }
  function contribution() { return {id:id(),text:'',action:'',method:'',result:'',evidence:'',reflection:'',attribution:'personal',reviewed:false,tags:[],interview:Object.fromEntries(INTERVIEW_KEYS.map(key=>[key,'']))}; }
  function experience(source='course') { if(!own(SOURCES,source)) throw new Error('Choose a known experience source.'); return {id:id(),source,section:SOURCES[source].section,role:'',organization:'',location:'',dates:'',status:source==='course'?'coursework':'completed',contributions:[]}; }
  function variant(state,variantId=state.selectedVariantId) { const result=state.variants.find(item=>item.id===variantId); if(!result) throw new Error('This résumé version does not exist.'); return result; }
  function cards(state) { return state.experiences.flatMap(experience=>experience.contributions.map(contribution=>({experience,contribution}))); }
  function lines(value) { return trim(value).split(/\r?\n+/).map(line=>line.replace(/^\s*[•*\-]\s+/,'').trim()).filter(Boolean); }

  // Reject values that cannot roundtrip instead of silently truncating or changing students' work.
  function fail(message) { throw new Error(message + ' Your current work has not changed.'); }
  function record(value,label) { if(!value || typeof value!=='object' || Array.isArray(value)) fail(label+' must be an object.');const prototype=Object.getPrototypeOf(value);if(prototype!==null&&Object.getPrototypeOf(prototype)!==null)fail(label+' must be a plain object.');return value; }
  function knownKeys(value,allowed,label) { for(const key of Object.keys(value)) if(!allowed.includes(key)) fail(label+' contains an unsupported field: '+key+'.'); }
  function string(value,max,label,fallback='') { if(value===undefined) return fallback; if(typeof value!=='string') fail(label+' must be text.'); if(value.length>max) fail(label+' exceeds '+max.toLocaleString('en-US')+' characters.'); if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/.test(value) || /[\ud800-\udbff](?![\udc00-\udfff])|(?<![\ud800-\udbff])[\udc00-\udfff]/u.test(value)) fail(label+' contains unsupported characters.'); return value; }
  function boolean(value,label,fallback=false) { if(value===undefined) return fallback; if(typeof value!=='boolean') fail(label+' must be true or false.'); return value; }
  function list(value,max,label,fallback=[]) { if(value===undefined) return fallback; if(!Array.isArray(value)) fail(label+' must be a list.'); if(value.length>max) fail(label+' exceeds '+max+' entries.'); return value; }
  function choice(value,values,label,fallback) { if(value===undefined) return fallback; if(!values.includes(value)) fail(label+' has an unsupported choice.'); return value; }
  function safeId(value,label,seen,optional=false) { const result=value===undefined&&optional?id():value; if(typeof result!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,95}$/.test(result)) fail(label+' has an invalid ID.'); if(seen.has(result)) fail(label+' has a duplicate ID.'); seen.add(result); return result; }
  function references(value,known,label) { const result=list(value,Math.max(LIMITS.contributions,LIMITS.skills),label); const seen=new Set(); for(const key of result){if(typeof key!=='string'||!known.has(key)) fail(label+' points to a missing item.'); if(seen.has(key)) fail(label+' contains a duplicate selection.');seen.add(key);} return [...result]; }
  function normalizeEducation(raw,seen,legacy=false) { record(raw,'Education entry'); if(!legacy) knownKeys(raw,['id','school','degree','dates','location','gpa','courses','honors'],'Education entry'); const result=education();result.id=safeId(raw.id,'Education entry',seen,legacy);for(const key of Object.keys(result).filter(key=>key!=='id'))result[key]=string(raw[key],LIMITS.field,'Education '+key);return result; }
  function normalizeContribution(raw,seen,legacy=false) {
    record(raw,'Contribution');knownKeys(raw,['id','text','action','method','result','evidence','reflection','attribution','reviewed','tags','interview'],'Contribution');const result=contribution();result.id=safeId(raw.id,'Contribution',seen,legacy);
    for(const key of ['text','action','method','result','evidence','reflection'])result[key]=string(raw[key],['evidence','reflection'].includes(key)?LIMITS.note:LIMITS.text,'Contribution '+key);
    result.attribution=choice(raw.attribution,ATTRIBUTION,'Attribution','personal');result.reviewed=boolean(raw.reviewed,'Claim review');result.tags=list(raw.tags,LIMITS.tags,'Contribution tags').map(value=>string(value,LIMITS.tag,'Tag'));
    if(new Set(result.tags).size!==result.tags.length) fail('Contribution tags contain duplicates.');
    const interview=raw.interview===undefined?{}:record(raw.interview,'Interview notes');knownKeys(interview,INTERVIEW_KEYS,'Interview notes');for(const key of INTERVIEW_KEYS)result.interview[key]=string(interview[key],LIMITS.note,'Interview '+key);return result;
  }
  function normalizeExperience(raw,seen) { record(raw,'Experience');knownKeys(raw,['id','source','section','role','organization','location','dates','status','contributions'],'Experience');const source=choice(raw.source,Object.keys(SOURCES),'Experience source','course');const result=experience(source);result.id=safeId(raw.id,'Experience',seen);result.section=choice(raw.section,['experience','projects','leadership'],'Experience section',SOURCES[source].section);result.status=choice(raw.status,STATUSES,'Project status',source==='course'?'coursework':'completed');for(const key of ['role','organization','location','dates'])result[key]=string(raw[key],LIMITS.field,'Experience '+key);result.contributions=list(raw.contributions,LIMITS.contributionsPerExperience,'Contributions in one experience').map(item=>normalizeContribution(item,seen));return result; }
  function normalizeV2(raw) {
    record(raw,'Proof backup');knownKeys(raw,['app','version','id','revision','updatedAt','remember','contact','education','experiences','skills','extras','variants','selectedVariantId'],'Proof backup');
    const seen=new Set(),state=blank();state.id=safeId(raw.id,'Project',seen);state.revision=raw.revision===undefined?0:raw.revision;if(!Number.isSafeInteger(state.revision)||state.revision<0)fail('Project revision is invalid.');state.updatedAt=string(raw.updatedAt,100,'Updated time');if(state.updatedAt&&!Number.isFinite(Date.parse(state.updatedAt)))fail('Updated time is invalid.');state.remember=boolean(raw.remember,'Local saving',true);
    const contact=record(raw.contact,'Contact details');knownKeys(contact,CONTACT_KEYS,'Contact details');for(const key of CONTACT_KEYS)state.contact[key]=string(contact[key],LIMITS.contact,'Contact '+key);
    state.education=list(raw.education,LIMITS.education,'Education entries').map(item=>normalizeEducation(item,seen));state.experiences=list(raw.experiences,LIMITS.experiences,'Experiences').map(item=>normalizeExperience(item,seen));
    const contributionIds=new Set(cards(state).map(item=>item.contribution.id));if(contributionIds.size>LIMITS.contributions)fail('The evidence library exceeds '+LIMITS.contributions+' contributions.');
    state.skills=list(raw.skills,LIMITS.skills,'Skills').map(rawSkill=>{record(rawSkill,'Skill');knownKeys(rawSkill,['id','name','category','practice','contributionIds'],'Skill');return {id:safeId(rawSkill.id,'Skill',seen),name:string(rawSkill.name,LIMITS.field,'Skill name'),category:choice(rawSkill.category,CATEGORIES,'Skill category','tools'),practice:choice(rawSkill.practice,PRACTICE,'Skill practice',''),contributionIds:references(rawSkill.contributionIds,contributionIds,'Skill evidence links')};});
    const skillIds=new Set(state.skills.map(item=>item.id));state.extras=string(raw.extras,LIMITS.extras,'Additional highlights');
    state.variants=list(raw.variants,LIMITS.variants,'Résumé versions').map(rawVariant=>{
      record(rawVariant,'Résumé version');knownKeys(rawVariant,['id','name','headline','summary','order','style','density','paperSize','contributionIds','skillIds','overrides','reviewedOverrides','requirements','jobDescription'],'Résumé version');const result=variantFactory();result.id=safeId(rawVariant.id,'Résumé version',seen);result.name=string(rawVariant.name,LIMITS.contact,'Version name','General resume');result.headline=string(rawVariant.headline,LIMITS.contact,'Professional focus');result.summary=string(rawVariant.summary,LIMITS.summary,'Short introduction');const order=list(rawVariant.order,ORDER.length,'Section order',[...ORDER]);if(order.length!==ORDER.length||new Set(order).size!==ORDER.length||order.some(key=>!ORDER.includes(key)))fail('Section order must include each section exactly once.');result.order=[...order];result.style=choice(rawVariant.style,['modern','classic'],'Type style','modern');result.density=choice(rawVariant.density,['comfortable','compact'],'Spacing','comfortable');result.paperSize=choice(rawVariant.paperSize,['letter','a4'],'Paper size','letter');result.contributionIds=references(rawVariant.contributionIds,contributionIds,'Version contribution selections');result.skillIds=references(rawVariant.skillIds,skillIds,'Version skill selections');
      const overrides=rawVariant.overrides===undefined?{}:record(rawVariant.overrides,'Version wording');result.overrides={};for(const key of Object.keys(overrides)){if(!contributionIds.has(key))fail('Version wording points to a missing contribution.');result.overrides[key]=string(overrides[key],LIMITS.text,'Version bullet wording');}result.reviewedOverrides=references(rawVariant.reviewedOverrides,contributionIds,'Version wording reviews');if(result.reviewedOverrides.some(key=>!own(result.overrides,key)))fail('A version wording review has no adapted wording.');
      result.requirements=list(rawVariant.requirements,LIMITS.requirements,'Opportunity requirements').map(item=>{record(item,'Requirement');knownKeys(item,['id','text','contributionIds'],'Requirement');return {id:safeId(item.id,'Requirement',seen),text:string(item.text,LIMITS.field,'Requirement text'),contributionIds:references(item.contributionIds,contributionIds,'Requirement evidence links')};});result.jobDescription=string(rawVariant.jobDescription,LIMITS.jobDescription,'Opportunity description');return result;
    });
    if(!state.variants.length)fail('A Proof backup must contain at least one résumé version.');if(typeof raw.selectedVariantId!=='string'||!state.variants.some(item=>item.id===raw.selectedVariantId))fail('The selected résumé version is missing.');state.selectedVariantId=raw.selectedVariantId;return state;
  }
  function legacyId(value,fallback,seen,label) { return safeId(value===undefined?fallback:value,label,seen); }
  function stableChild(parent,suffix) { if(parent.length+suffix.length+1<=96)return parent+'-'+suffix;let hash=2166136261;for(const char of parent){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return 'legacy-'+(hash>>>0).toString(36)+'-'+suffix; }
  function legacySkillNames(value) { const names=[];let current='',depth=0;for(const character of value){if(character==='(')depth++;else if(character===')')depth=Math.max(0,depth-1);if(depth===0&&/[\n,;]/.test(character)){if(trim(current))names.push(trim(current));current='';}else current+=character;}if(trim(current))names.push(trim(current));return names; }
  function migrateV1(raw) {
    if(!raw.contact||!Array.isArray(raw.education)||!Array.isArray(raw.experiences))fail('Choose a valid Proof backup (version 1 or 2).');const state=blank(),seen=new Set([state.id]),v=state.variants[0];seen.add(v.id);const contact=record(raw.contact,'Contact details');for(const key of CONTACT_KEYS)state.contact[key]=string(contact[key],LIMITS.contact,'Contact '+key);v.headline=string(contact.headline,LIMITS.contact,'Professional focus');v.summary=string(contact.summary,LIMITS.summary,'Short introduction');state.remember=boolean(raw.remember,'Local saving',true);
    state.education=list(raw.education,LIMITS.education,'Education entries').map((item,index)=>{record(item,'Education entry');return normalizeEducation({...item,id:legacyId(item.id,'legacy-education-'+index,new Set(),'Education entry')},seen,true);});
    state.experiences=list(raw.experiences,LIMITS.experiences,'Experiences').map((old,index)=>{record(old,'Experience');const source=own(SOURCES,old.source)?old.source:'work';const result=experience(source);result.id=legacyId(old.id,'legacy-experience-'+index,seen,'Experience');result.section=choice(old.section,['experience','projects','leadership'],'Experience section',SOURCES[source].section);for(const key of ['role','organization','location','dates'])result[key]=string(old[key],LIMITS.field,'Experience '+key);const bulletText=string(old.bullets,LIMITS.text,'Résumé bullets'),bulletLines=lines(bulletText);if(bulletLines.length>LIMITS.contributionsPerExperience)fail('One legacy experience exceeds '+LIMITS.contributionsPerExperience+' bullets.');const supplied={};for(const key of ['action','method','result','evidence','reflection'])supplied[key]=string(old[key],['evidence','reflection'].includes(key)?LIMITS.note:LIMITS.text,'Experience '+key);const include=boolean(old.include,'Include experience',true),reviewed=boolean(old.verified,'Legacy claim review');
      const texts=bulletLines.length?bulletLines:Object.values(supplied).some(trim)?['']:[];result.contributions=texts.map((text,bulletIndex)=>{const item=contribution();item.id=safeId(stableChild(result.id,'c'+bulletIndex),'Contribution',seen);item.text=text;if(bulletIndex===0)Object.assign(item,supplied);item.reviewed=!!text&&reviewed;if(include&&text)v.contributionIds.push(item.id);return item;});return result;});
    const skills=raw.skills===undefined?{}:record(raw.skills,'Skills');for(const category of CATEGORIES){const names=legacySkillNames(string(skills[category],LIMITS.text,'Skills '+category));for(const [index,name]of names.entries()){const item={id:safeId('legacy-skill-'+category+'-'+index,'Skill',seen),name,category,practice:'',contributionIds:[]};state.skills.push(item);v.skillIds.push(item.id);}}
    state.extras=string(raw.extras,LIMITS.extras,'Additional highlights');if(raw.order!==undefined){const order=list(raw.order,ORDER.length,'Section order');if(order.length!==ORDER.length||new Set(order).size!==ORDER.length||order.some(key=>!ORDER.includes(key)))fail('Section order must include each section exactly once.');v.order=[...order];}v.style=choice(raw.style,['modern','classic'],'Type style','modern');v.density=choice(raw.density,['comfortable','compact'],'Spacing','comfortable');return normalizeV2(state);
  }
  function normalize(raw) { record(raw,'Proof backup');if(raw.app!=='proof-resume'||![1,2].includes(raw.version))fail('Choose a valid Proof backup (version 1 or 2).');return raw.version===1?migrateV1(raw):normalizeV2(raw); }

  function sentencePart(value) { return trim(value).replace(/[.;\s]+$/,''); }
  function capitalize(value) { return value?value.charAt(0).toUpperCase()+value.slice(1):''; }
  function continuingAction(value) { return /^(analyzed|analysed|assessed|assisted|built|compared|coordinated|created|designed|developed|documented|drafted|edited|evaluated|explained|gathered|identified|implemented|improved|led|maintained|measured|modeled|modelled|organized|organised|planned|prepared|presented|produced|researched|resolved|reviewed|scheduled|supported|tested|tracked|trained|wrote)\b/i.test(value)?value.charAt(0).toLowerCase()+value.slice(1):value; }
  function draft(item,mode='action') { const action=sentencePart(item.action),method=sentencePart(item.method),result=sentencePart(item.result);if(!action)return '';const withMethod=method?( /^(using|with|through|by|in)\b/i.test(method)?' '+method:' using '+method):'';if(mode==='result'&&result)return capitalize(result)+'; '+continuingAction(action)+withMethod+'.';if(mode==='method'&&method)return capitalize(/^(using|with|through|by|in)\b/i.test(method)?method:'Using '+method)+', '+continuingAction(action)+(result?'; '+result:'')+'.';return capitalize(action)+withMethod+(result?'; '+result:'')+'.'; }
  function feedback(item,text=item.text) {
    const value=trim(text),items=[];if(!value)return [{text:'Start with one thing you personally did. A useful deliverable counts even without a number.',good:false}];
    if(/^(responsible for|duties included|helped with|worked on)\b/i.test(value))items.push({text:'Start with your own action. What did you create, organize, analyze, explain, or change?',good:false});
    if(/^(i|my|we|our)\b/i.test(value))items.push({text:'For résumé wording, try starting with the action instead of a personal pronoun.',good:false});
    if(/\b(hard.?working|team player|go.getter|results.driven|passionate|synergy|rockstar|dynamic professional|detail.oriented)\b/i.test(value))items.push({text:'Replace a broad label with an example that lets the reader see that quality.',good:false});
    const wordCount=value.split(/\s+/).length;if(wordCount>42)items.push({text:'This bullet has '+wordCount+' words. Try one contribution and keep the clearest details.',good:false});if(wordCount<8)items.push({text:'Add the object of your work, a method, or a useful detail so the reader can picture this contribution.',good:false});
    if(/\d/.test(value))items.push({text:'Check numbers in this wording. Separate measured results, estimates, and the size of your work.',good:false});
    if(item.attribution==='team'&&!/\b(team|collaborat\w*|co-led|joint\w*|supported)\b/i.test(value))items.push({text:'This is marked as a team contribution. Credit the shared outcome and make your own part clear.',good:false});
    if(/\b(increased|decreased|improved|reduced|boosted|grew)\b/i.test(value)&&!/(\d|\bfrom\b|\bby\b|\bcompared\b)/i.test(value))items.push({text:'You describe a change. What comparison, observation, or feedback supports it?',good:false});
    if(trim(item.evidence))items.push({text:'You have a private evidence note to help recall the story behind this claim.',good:true});if(item.reviewed)items.push({text:'You marked this claim as reviewed. Recheck it whenever the wording changes.',good:true});if(!items.length)items.push({text:'This wording avoids the common patterns checked here. Read it aloud and confirm it names your contribution.',good:true});return items;
  }
  function content(state,variantId=state.selectedVariantId) {
    const current=variant(state,variantId),selected=new Set(current.contributionIds),selectedSkills=new Set(current.skillIds);
    const sections=current.order.map(key=>{let entries=[];if(key==='education')entries=state.education.filter(item=>trim(item.school)||trim(item.degree)).map(item=>({id:item.id,title:trim(item.school),sub:[item.degree,item.location,item.dates].map(trim).filter(Boolean).join(' | '),bullets:[trim(item.gpa)?'GPA: '+trim(item.gpa):'',trim(item.courses)?'Relevant coursework: '+trim(item.courses):'',trim(item.honors)].filter(Boolean),bulletIds:[]}));
      else if(['experience','projects','leadership'].includes(key))entries=state.experiences.filter(item=>item.section===key).map(item=>{const included=item.contributions.filter(claim=>selected.has(claim.id)).map(claim=>({id:claim.id,text:trim(own(current.overrides,claim.id)?current.overrides[claim.id]:claim.text)})).filter(claim=>claim.text);return {id:item.id,title:[item.role,item.organization].map(trim).filter(Boolean).join(' | '),sub:[item.location,item.dates,{proposal:'Proposal',simulation:'Simulation',prototype:'Prototype'}[item.status]||''].map(trim).filter(Boolean).join(' | '),bullets:included.map(claim=>claim.text),bulletIds:included.map(claim=>claim.id)};}).filter(item=>item.bullets.length);
      else if(key==='skills')entries=CATEGORIES.map(category=>({id:'skill-category-'+category,title:'',sub:{tools:'Tools',methods:'Methods',languages:'Languages'}[category]+': '+state.skills.filter(item=>selectedSkills.has(item.id)&&item.category===category&&trim(item.name)).map(item=>trim(item.name)).join(', '),bullets:[],bulletIds:[]})).filter((item,index)=>state.skills.some(skill=>selectedSkills.has(skill.id)&&skill.category===CATEGORIES[index]&&trim(skill.name)));
      else if(key==='extras')entries=lines(state.extras).map((text,index)=>({id:'extra-'+index,title:'',sub:text,bullets:[],bulletIds:[]}));return {key,title:LABELS[key],entries};}).filter(section=>section.entries.length);
    return {name:trim(state.contact.name),contact:['location','email','phone','linkedin','portfolio'].map(key=>trim(state.contact[key])).filter(Boolean),headline:trim(current.headline),summary:trim(current.summary),sections};
  }
  function countWords(state,variantId=state.selectedVariantId) { const result=content(state,variantId);return [result.name,...result.contact,result.headline,result.summary,...result.sections.flatMap(section=>[section.title,...section.entries.flatMap(entry=>[entry.title,entry.sub,...entry.bullets])])].join(' ').trim().split(/\s+/).filter(Boolean).length; }
  function assessments(state) { const current=variant(state),projected=content(state),visible=new Set(projected.sections.flatMap(section=>section.entries.flatMap(entry=>entry.bulletIds))),included=cards(state).filter(item=>visible.has(item.contribution.id));return [
    {name:'Make it easy to reach you',ready:!!trim(state.contact.name)&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trim(state.contact.email)),description:'Add your name and a valid email address.',step:'details'},
    {name:'Give your education context',ready:state.education.some(item=>trim(item.school)&&trim(item.degree)),description:'Include your school and degree or program.',step:'education'},
    {name:'Show your contribution',ready:included.length>0,description:'Select at least one finished contribution for this résumé version.',step:'library'},
    {name:'Review the claims you selected',ready:included.length>0&&included.every(item=>own(current.overrides,item.contribution.id)?current.reviewedOverrides.includes(item.contribution.id):item.contribution.reviewed),description:'Review every selected claim, including any wording adjusted for this version.',step:'library'},
    {name:'Name skills you can demonstrate',ready:state.skills.some(item=>current.skillIds.includes(item.id)&&trim(item.name)),description:'Select concrete skills to discuss or demonstrate.',step:'skills'}
  ]; }
  const ALIASES = [
    {terms:['excel','microsoft excel'],signals:['excel','microsoft excel']},
    {terms:['canva'],signals:['canva']},
    {terms:['google analytics','ga4'],signals:['google analytics','ga4']},
    {terms:['python'],signals:['python']},
    {terms:['sql'],signals:['sql']},
    {terms:['javascript'],signals:['javascript']},
    {terms:['data analysis','data analytics','analyze data','analyse data'],signals:['data analysis','data analytics','analyzed','analysed','pivot tables','statistical analysis']},
    {terms:['spreadsheets','spreadsheet'],signals:['excel','google sheets','spreadsheet','pivot tables']},
    {terms:['social media','social marketing'],signals:['social media','instagram','facebook','tiktok','linkedin campaign','content calendar']},
    {terms:['content creation','content development'],signals:['content calendar','copywriting','canva','campaign mockups','wrote','video editing']},
    {terms:['customer service','customer support'],signals:['customer service','customer questions','customer order','returns guide','customer support']},
    {terms:['project management','project coordination'],signals:['project plan','timeline','coordinated','volunteer assignments','project management']},
    {terms:['research','market research'],signals:['research','survey','interviewed','interviews','primary sources']},
    {terms:['communication','communications'],signals:['presented','presentation','explained','guide','instructions']},
    {terms:['leadership'],signals:['led','co-led','coordinated','trained','mentored','organized an event']}
  ];
  function searchText(value) { return trim(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim(); }
  function phrase(haystack,needle) { return !!needle&&(' '+haystack+' ').includes(' '+needle+' '); }
  function requirementMatches(state,requirementText) { const requirement=searchText(requirementText);if(!requirement)return [];const matchingAliases=ALIASES.filter(group=>group.terms.some(term=>phrase(requirement,searchText(term))));return cards(state).filter(({contribution:claim})=>{const haystack=searchText([claim.text,...claim.tags].join(' '));return trim(claim.text)&&(phrase(haystack,requirement)||matchingAliases.some(group=>group.signals.some(signal=>phrase(haystack,searchText(signal)))));}).map(item=>item.contribution.id); }
  function rehearsal(item,text=item.text) { const questions=['What was the situation, and who needed this work?','What were you personally responsible for?','Walk through one decision or tradeoff you made.','What did you deliver, and who used it?','What would you change if you did it again?'];if(/\d/.test(trim(text)))questions.splice(4,0,'How was each number measured or estimated? What was the baseline?');if(item.attribution==='team'||item.attribution==='support')questions.splice(2,0,'What did the team accomplish, and which part did you own or support?');questions.push('What evidence or person could help you explain this claim?');return questions; }
  function metric(before,after) { const numeric=(value,label)=>{if(typeof value!=='number'&&typeof value!=='string'||typeof value==='string'&&!value.trim())throw new Error('Enter a finite '+label+' value.');const result=Number(value);if(!Number.isFinite(result))throw new Error('Enter a finite '+label+' value.');return result;};const first=numeric(before,'before'),last=numeric(after,'after'),difference=last-first,percent=first===0?null:difference/Math.abs(first)*100;if(!Number.isFinite(difference)||percent!==null&&!Number.isFinite(percent))throw new Error('Those values exceed the calculator range.');return {difference:Number(difference.toPrecision(15)),percent:percent===null?null:Number(percent.toPrecision(15))}; }
  function normalizeHandoff(raw) {
    record(raw,'Evidence handoff');knownKeys(raw,['app','version','title','source','status','contributions'],'Evidence handoff');if(raw.app!=='proof-evidence'||raw.version!==1)fail('Choose a proof-evidence version 1 handoff.');const title=string(raw.title,LIMITS.field,'Project title');if(!trim(title))fail('The evidence handoff needs a project title.');if(!own(raw,'source')||!own(raw,'status'))fail('The evidence handoff needs a source and project status.');const source=choice(raw.source,Object.keys(SOURCES),'Evidence source'),status=choice(raw.status,STATUSES,'Evidence status');const input=list(raw.contributions,LIMITS.contributionsPerExperience,'Handoff contributions');if(!input.length)fail('The evidence handoff needs at least one contribution.');const result=experience(source);result.organization=title;result.status=status;result.contributions=input.map(rawClaim=>{record(rawClaim,'Handoff contribution');knownKeys(rawClaim,['text','action','method','result','evidence','reflection'],'Handoff contribution');const claim=contribution();for(const key of ['text','action','method','result','evidence','reflection'])claim[key]=string(rawClaim[key],['evidence','reflection'].includes(key)?LIMITS.note:LIMITS.text,'Handoff '+key);if(!trim(claim.text)&&!trim(claim.action))fail('Each handoff contribution needs an action or finished text.');if(!trim(claim.text))claim.text=draft(claim);if(claim.text.length>LIMITS.text)fail('One assembled handoff bullet exceeds '+LIMITS.text+' characters.');return claim;});return [result];
  }
  function sample() {
    const state=blank();state.contact={name:'Jordan Rivera',location:'Edinburg, TX',email:'jordan.rivera@example.com',phone:'(956) 555-0142',linkedin:'linkedin.com/in/jordan-rivera-example',portfolio:''};state.education=[{...education(),school:'Rio Valley University',degree:'BBA in Marketing',dates:'Expected May 2027',courses:'Consumer Behavior, Business Analytics, Marketing Research'}];
    const project=experience('course');Object.assign(project,{role:'Research & Strategy Lead',organization:'Campus Café Course Project',dates:'January to May 2026',status:'proposal'});const first=contribution();Object.assign(first,{text:'Analyzed 86 student survey responses in Excel to identify three purchase barriers; presented recommendations to the café owner.',action:'Analyzed 86 student survey responses',method:'Excel pivot tables',result:'identified three purchase barriers and presented recommendations to the café owner',evidence:'Fictional example: survey workbook, course presentation, and campaign mockups.',reviewed:true,tags:['research','Excel','data analysis']});const second=contribution();Object.assign(second,{text:'Created a four-week content calendar and six campaign mockups in Canva for a student marketing proposal.',reviewed:true,tags:['content planning','Canva']});project.contributions=[first,second];
    const work=experience('work');Object.assign(work,{role:'Sales Associate',organization:'Valley Outfitters',dates:'June 2025 to Present',status:'ongoing'});const third=contribution();Object.assign(third,{text:'Organized weekly stock checks across four product categories and flagged discrepancies for the shift lead.',reviewed:true});const fourth=contribution();Object.assign(fourth,{text:'Created a one-page returns guide that two new team members used during onboarding.',reviewed:true});work.contributions=[third,fourth];
    const campus=experience('campus');Object.assign(campus,{role:'Event Volunteer',organization:'Student Business Society',dates:'September 2025 to May 2026'});const fifth=contribution();Object.assign(fifth,{text:'Coordinated check-in for a campus networking event with 70 attendees and prepared name tags and registration materials.',reviewed:true});campus.contributions=[fifth];state.experiences=[project,work,campus];state.skills=[{id:id(),name:'Excel (pivot tables)',category:'tools',practice:'independent',contributionIds:[first.id]},{id:id(),name:'Canva',category:'tools',practice:'repeated',contributionIds:[second.id]},{id:id(),name:'Survey analysis',category:'methods',practice:'independent',contributionIds:[first.id]},{id:id(),name:'English (fluent), Spanish (conversational)',category:'languages',practice:'',contributionIds:[]}];const current=variant(state);current.contributionIds=cards(state).map(item=>item.contribution.id);current.skillIds=state.skills.map(item=>item.id);return state;
  }
  function template() { const state=blank();state.contact={name:'YOUR NAME',email:'you@example.com',phone:'Your phone',location:'City, State',linkedin:'',portfolio:'Your portfolio URL'};state.education=[{...education(),school:'University or college',degree:'Degree and major',dates:'Expected graduation month and year',courses:'Selected courses relevant to your interests'}];const project=experience('course');project.role='Your project role';project.organization='Project or course name';project.dates='Month Year';project.contributions=[{...contribution(),text:'Describe what you created, analyzed, organized, or improved.'},{...contribution(),text:'Explain your method and what you delivered, using accurate details.'}];const work=experience('work');work.role='Your role';work.organization='Employer or organization';work.dates='Month Year to Month Year';work.contributions=[{...contribution(),text:'Name a specific contribution and who benefited from it.'}];state.experiences=[project,work];state.skills=[{id:id(),name:'Tools you can demonstrate',category:'tools',practice:'',contributionIds:[]},{id:id(),name:'Methods you have practiced',category:'methods',practice:'',contributionIds:[]}];const current=variant(state);current.contributionIds=cards(state).map(item=>item.contribution.id);current.skillIds=state.skills.map(item=>item.id);return state; }
  return {ORDER,LABELS,SOURCES,LIMITS,STATUSES,PRACTICE,ATTRIBUTION,CATEGORIES,id,blank,education,experience,contribution,variantFactory,variant,cards,normalize,normalizeHandoff,draft,feedback,content,countWords,assessments,requirementMatches,rehearsal,metric,sample,template,lines,esc};
})();
